# Generated by Django 3.2.6 on 2021-08-05 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='name',
            new_name='nome',
        ),
    ]
